### ISSUE TITLE
Overfitting?

### ISSUE THREAD

**Issue by insaf-ismath** [insaf-ismath/StrategicLearningHW3#2]
![image](https://user-images.githubusercontent.com/25426807/100481667-81f35880-30fd-11eb-84be-104b19ef6810.png)

After patching the 1/(no_users) issue, it showed the above results. n_epochs = 500
Although training accuracy is increased up to high 90s, the test accuracy converges to 0.88, so I guess overfitting? any thoughts @Praneeth?

**Comment by insaf-ismath** [comment]
loss plot

![image](https://user-images.githubusercontent.com/25426807/100482216-478abb00-30ff-11eb-839b-e9232e00da02.png)

**Comment by insaf-ismath** [comment]
Few final training outputs.

![image](https://user-images.githubusercontent.com/25426807/100482244-612c0280-30ff-11eb-8247-43390ffd0590.png)

**Comment by psusarla95** [comment]
Hi @insaf-ismath, I ran your code now and I think the code is now running perfectly. I don't think there is any overfitting involved. the nature of both training and test accuracy curves are looking similar. The slight difference in training and testing accuracy should be fine I guess.

**Comment by insaf-ismath** [comment]
Ok great. Then I'll close the issue.
